alias ls='exa --icons -a --group-directories-first'
alias grep='grep --color=auto'
alias reboot='doas reboot'
alias poweroff='doas poweroff'
alias pacman='doas pacman'
alias mount='doas mount'
alias umount='doas umount'
alias spt='spotifyd && spt'
alias pipes='pipes.sh -p 7 -t 0 -f 60 -R -r 0'
alias screenshot='import'
alias gotop='gotop -s -r 600ms --nvidia'
alias update-grub='doas grub-mkconfig -o /boot/grub/grub.cfg'
alias weather='curl wttr.in/düsseldorf'
alias cp='cp -v'
alias checkbashisms='checkbashisms -nplx'
alias syncmonero='monerod --zmq-pub tcp://127.0.0.1:18083 --out-peers 64 --in-peers 32 --add-priority-node=node.supportxmr.com:18080 --add-priority-node=nodes.hashvault.pro:18080 --disable-dns-checkpoints --enable-dns-blocklist --prune-blockchain'
alias bg1='feh --no-fehbg --bg-fill "/home/finn/.config/feh/bg1.png" "/home/finn/.config/feh/bg2.png"'
alias bg2='feh --no-fehbg --bg-fill "/home/finn/.config/feh/monitor1.png" "/home/finn/.config/feh/monitor2.png"'
